import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
    root: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#047454',
        alignItems: 'center',
        justifyContent: 'center',
    },
    rootDark: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#044936',
        alignItems: 'center',
        justifyContent: 'center',
    },
    loginBox: {
        width: 433,
        height: 529,
        padding: 24,
        borderRadius: 16,
        backgroundColor: '#f0fdf4',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.8,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
    },
    darkBox: {
        backgroundColor: '#1f1f1f',
    },
    logo: {
        width: 250,
        height: 150,
        marginBottom: 16,
    },
    title: {
        fontSize: 32,
        fontWeight: 'bold',
        marginBottom: 40,
        marginTop: 15,
        color: '#000',
    },
    titleDark: {
        color: '#fff',
        fontSize: 32,
        fontWeight: 'bold',
        marginBottom: 40,
        marginTop: 15,
    },
    input: {
        width: '100%',
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 6,
        marginBottom: 20,
        backgroundColor: '#fff',
        color: '#000',
    },
    inputDark: {
        width: '100%',
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderWidth: 1,
        borderRadius: 6,
        marginBottom: 20,
        backgroundColor: '#2a2a2a',
        color: '#f5f5f5',
        borderColor: '#444',
    },

    button: {
        marginTop: 40,
        backgroundColor: '#047454',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 6,
    },
    buttonDark: {
        marginTop: 40,
        backgroundColor: '#2a2a2a',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 6,
    },
    buttonText: {
        color: '#fff',
        fontSize: 20,
    },
    themeSwitch: {
        position: 'absolute',
        bottom: 20,
        left: 20,
        zIndex: 10,
    },

    switchIcon: {
        fontSize: 24,
    },
})
